// Holds and short and long names for teams
class Pair{
    constructor(name, shortName){
      this.name = name;
      this.shortName = shortName
    }
  }

  // Set Team names
  let teamNames = [];
  teamNames.push(new Pair("Philadelphia Eagles", "PHI")); //1
  teamNames.push(new Pair("Dallas Cowboys", "DAL")); //2
  teamNames.push(new Pair("Los Angeles Chargers", "LAC")); //3
  teamNames.push(new Pair("Kansas City Chiefs", "KC")); //4
  teamNames.push(new Pair("Atlanta Falcons", "ATL")); //5
  teamNames.push(new Pair("Tampa Bay Buccaneers", "TB")); //6
  teamNames.push(new Pair("Cleveland Browns", "CLE")); //7
  teamNames.push(new Pair("Cincinnati Bengals", "CIN")); //8
  teamNames.push(new Pair("Indianapolis Colts", "IND")); //9
  teamNames.push(new Pair("Miami Dolphins", "MIA")); //10
  teamNames.push(new Pair("New England Patriots", "NE")); //11
  teamNames.push(new Pair("Las Vegas Raiders", "LV")); //12
  teamNames.push(new Pair("New Orleans Saints", "NO")); //13
  teamNames.push(new Pair("Arizona Cardinals", "ARI")); //14
  teamNames.push(new Pair("New York Jets", "NYJ")); //15
  teamNames.push(new Pair("Pittsburgh Steelers", "PIT")); //16
  teamNames.push(new Pair("Washington Commanders", "WAS")); //17
  teamNames.push(new Pair("New York Giants", "NYG")); //18
  teamNames.push(new Pair("Jacksonville Jaguars", "JAX")); //19
  teamNames.push(new Pair("Carolina Panthers", "CAR")); //20
  teamNames.push(new Pair("Denver Broncos", "DEN")); //21
  teamNames.push(new Pair("Tennessee Titans", "TEN")); //22
  teamNames.push(new Pair("Seattle Seahawks", "SEA")); //23
  teamNames.push(new Pair("San Francisco 49ers", "SF")); //24
  teamNames.push(new Pair("Green Bay Packers", "GB")); //25
  teamNames.push(new Pair("Detroit Lions", "DET")); //26
  teamNames.push(new Pair("Los Angeles Rams", "LAR")); //27
  teamNames.push(new Pair("Houston Texans", "HOU")); //28
  teamNames.push(new Pair("Buffalo Bills", "BUF")); //29
  teamNames.push(new Pair("Baltimore Ravens", "BAL")); //30
  teamNames.push(new Pair("Chicago Bears", "CHI")); //31
  teamNames.push(new Pair("Minnesota Vikings", "MIN")); //32

  
  function GetShortName(name) {
    const match = teamNames.find(n => n.name === name);
    return match ? match.shortName : null;
  }
  

  class Team{
    constructor(name, shortName, wins, losses, ties)
    {
      this.name = name;
      this.shortName = shortName;
      this.wins = wins;
      this.losses = losses;
      this.ties = ties;

      this.getPngImageDirectory();
    }

    getName() {
      return this.name;
    }

    getPngImageDirectory()
    {
        this.pngImageName = "Images/" + this.shortName + ".png";
    }
  }

  // Fill Teamarray
  let TeamArray = [];
  teamNames.forEach(pair => {
    TeamArray.push(new Team(pair.name, pair.shortName, 0, 0, 0));
  });

  class Game
  {
    constructor(away, home){
        this.away = away;
        this.home = home;
    }
  }

  class Week
  {
    constructor (week){
        this.week = week;
        this.games = [];
    }
    AddGame(away, home) {
        this.games.push(new Game(away, home));
    }
  }

  class Season
  {
    AddWeek(week){
        this.weeks.push(week);
    }
  }

  let week1 = new Week(1);
  week1.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week1.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week1.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week1.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week1.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week1.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week1.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week1.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week1.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week1.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week1.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week1.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week1.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week1.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week1.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week1.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  let week2 = new Week(2);
  week2.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week2.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week2.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week2.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week2.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week2.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week2.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week2.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week2.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week2.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week2.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week2.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week2.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week2.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week2.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week2.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  let week3 = new Week(3);
  week3.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week3.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week3.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week3.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week3.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week3.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week3.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week3.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week3.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week3.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week3.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week3.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week3.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week3.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week3.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week3.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  let week4 = new Week(4);
  week4.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week4.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week4.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week4.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week4.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week4.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week4.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week4.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week4.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week4.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week4.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week4.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week4.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week4.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week4.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week4.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  let week5 = new Week(5);
  week5.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week5.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week5.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week5.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week5.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week5.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week5.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week5.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week5.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week5.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week5.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week5.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week5.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week5.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  let week6 = new Week(6);
  week6.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week6.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week6.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week6.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week6.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week6.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week6.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week6.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week6.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week6.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week6.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week6.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week6.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week6.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week6.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  let week7 = new Week(7);
  week7.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week7.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week7.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week7.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week7.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week7.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week7.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week7.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week7.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week7.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week7.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week7.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week7.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week7.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week7.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  let week8 = new Week(8);
  week8.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week8.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week8.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week8.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week8.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week8.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week8.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week8.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week8.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week8.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week8.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week8.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week8.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  let week9 = new Week(9);
  week9.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week9.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week9.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week9.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week9.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week9.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week9.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week9.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week9.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week9.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week9.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week9.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week9.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week9.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  let week10 = new Week(10);
  week10.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week10.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week10.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week10.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week10.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week10.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week10.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week10.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week10.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week10.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week10.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week10.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week10.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week10.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  let week11 = new Week(11);
  week11.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week11.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week11.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week11.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week11.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week11.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week11.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week11.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week11.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week11.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week11.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week11.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week11.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week11.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week11.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  let week12 = new Week(12);
  week12.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week12.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week12.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week12.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week12.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week12.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week12.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week12.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week12.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week12.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week12.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week12.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week12.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week12.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  let week13 = new Week(13);
  week13.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week13.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week13.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week13.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week13.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  week13.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week13.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week13.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week13.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week13.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week13.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week13.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week13.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week13.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week13.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week13.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  let week14 = new Week(14);
  week14.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week14.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week14.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week14.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week14.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week14.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week14.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week14.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week14.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week14.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week14.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week14.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week14.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week14.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  let week15 = new Week(15);
  week15.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week15.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week15.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week15.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week15.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week15.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week15.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week15.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week15.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week15.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week15.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week15.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week15.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week15.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  week15.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week15.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  let week16 = new Week(16);
  week16.AddGame(new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  week16.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week16.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week16.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  )
  week16.AddGame(new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week16.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week16.AddGame(new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week16.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  )
  week16.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week16.AddGame(new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week16.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week16.AddGame(new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  , new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  )
  week16.AddGame(new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week16.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  )
  week16.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  )
  week16.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  )
  let week17 = new Week(17);
  week17.AddGame(new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week17.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week17.AddGame(new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  , new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  )
  week17.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week17.AddGame(new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week17.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  )
  week17.AddGame(new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  , new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  )
  week17.AddGame(new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week17.AddGame(new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  , new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  )
  week17.AddGame(new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week17.AddGame(new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  , new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  )
  week17.AddGame(new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  , new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  )
  week17.AddGame(new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  , new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  )
  week17.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  )
  week17.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  )
  week17.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  )
  let week18 = new Week(18);
  week18.AddGame(new Team("Atlanta Falcons", GetShortName("Atlanta Falcons"), 0, 0, 0)
  , new Team("New Orleans Saints", GetShortName("New Orleans Saints"), 0, 0, 0)
  )
  week18.AddGame(new Team("Buffalo Bills", GetShortName("Buffalo Bills"), 0, 0, 0)
  , new Team("New York Jets", GetShortName("New York Jets"), 0, 0, 0)
  )
  week18.AddGame(new Team("Chicago Bears", GetShortName("Chicago Bears"), 0, 0, 0)
  , new Team("Detroit Lions", GetShortName("Detroit Lions"), 0, 0, 0)
  )
  week18.AddGame(new Team("Cincinnati Bengals", GetShortName("Cincinnati Bengals"), 0, 0, 0)
  , new Team("Cleveland Browns", GetShortName("Cleveland Browns"), 0, 0, 0)
  )
  week18.AddGame(new Team("Denver Broncos", GetShortName("Denver Broncos"), 0, 0, 0)
  , new Team("Los Angeles Chargers", GetShortName("Los Angeles Chargers"), 0, 0, 0)
  )
  week18.AddGame(new Team("Las Vegas Raiders", GetShortName("Las Vegas Raiders"), 0, 0, 0)
  , new Team("Kansas City Chiefs", GetShortName("Kansas City Chiefs"), 0, 0, 0)
  )
  week18.AddGame(new Team("Los Angeles Rams", GetShortName("Los Angeles Rams"), 0, 0, 0)
  , new Team("Arizona Cardinals", GetShortName("Arizona Cardinals"), 0, 0, 0)
  )
  week18.AddGame(new Team("Minnesota Vikings", GetShortName("Minnesota Vikings"), 0, 0, 0)
  , new Team("Green Bay Packers", GetShortName("Green Bay Packers"), 0, 0, 0)
  )
  week18.AddGame(new Team("New England Patriots", GetShortName("New England Patriots"), 0, 0, 0)
  , new Team("Miami Dolphins", GetShortName("Miami Dolphins"), 0, 0, 0)
  )
  week18.AddGame(new Team("New York Giants", GetShortName("New York Giants"), 0, 0, 0)
  , new Team("Dallas Cowboys", GetShortName("Dallas Cowboys"), 0, 0, 0)
  )
  week18.AddGame(new Team("Philadelphia Eagles", GetShortName("Philadelphia Eagles"), 0, 0, 0)
  , new Team("Washington Commanders", GetShortName("Washington Commanders"), 0, 0, 0)
  )
  week18.AddGame(new Team("Pittsburgh Steelers", GetShortName("Pittsburgh Steelers"), 0, 0, 0)
  , new Team("Baltimore Ravens", GetShortName("Baltimore Ravens"), 0, 0, 0)
  )
  week18.AddGame(new Team("San Francisco 49ers", GetShortName("San Francisco 49ers"), 0, 0, 0)
  , new Team("Seattle Seahawks", GetShortName("Seattle Seahawks"), 0, 0, 0)
  )
  week18.AddGame(new Team("Tampa Bay Buccaneers", GetShortName("Tampa Bay Buccaneers"), 0, 0, 0)
  , new Team("Carolina Panthers", GetShortName("Carolina Panthers"), 0, 0, 0)
  )
  week18.AddGame(new Team("Jacksonville Jaguars", GetShortName("Jacksonville Jaguars"), 0, 0, 0)
  , new Team("Tennessee Titans", GetShortName("Tennessee Titans"), 0, 0, 0)
  )
  week18.AddGame(new Team("Houston Texans", GetShortName("Houston Texans"), 0, 0, 0)
  , new Team("Indianapolis Colts", GetShortName("Indianapolis Colts"), 0, 0, 0)
  )
  
 
  let season = new Season();
  season.AddWeek(week1);
  season.AddWeek(week2);
  season.AddWeek(week3);
  season.AddWeek(week4);
  season.AddWeek(week5);
  season.AddWeek(week6);
  season.AddWeek(week7);
  season.AddWeek(week8);
  season.AddWeek(week9);
  season.AddWeek(week10);
  season.AddWeek(week11);
  season.AddWeek(week12);
  season.AddWeek(week13);
  season.AddWeek(week14);
  season.AddWeek(week15);
  season.AddWeek(week16);
  season.AddWeek(week17);
  season.AddWeek(week18);
  
